Repository thoth-station/workflows, pull requests merged in 2019-11, with the labels that each got.

#2 Inspection batch with failure
  examples/inspection-batch-with-failure.yaml
Labels: approved, size/M

#1 Add inspection-batch workflow example
  examples/inspection-batch.yaml
Labels: approved, size/M

#13 Added example workflow for resource validation
  examples/resource-validate.yaml
Labels: approved, size/M

#14 Added inspection workflow-templates
  examples/templates/template-collect-outputs.yaml
  templates/inspection-build-template.yaml
  templates/inspection-results-template.yaml
  templates/inspection-run-template.yaml
Labels: approved, size/L

#16 Moved notebooks to thoth-station/notebooks repo
  README.md
  notebooks/client.ipynb
Labels: approved

#17 now with 125% more standard project configuration files!
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new_deployment.md
Labels: size/M

#11 Implemented a solver and syncer workflow
  .coafile
  README.md
  argo/solve_and_sync.yaml
  argo/templates/solver-rhel-8.0-py36.yaml
  argo/templates/sync.yaml
  reconcile.sh
Labels: approved, size/L

#18 Fix/solver workflow typos
  argo/solve_and_sync.yaml
  reconcile.sh
Labels: approved, size/S
